apiVersion: apps/v1
kind: Deployment
metadata:
  name: lytx
  labels:
    app: lytx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lytx
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: lytx
    spec:     # pod spec
      containers:
        - name: lytx
          image: nathanborik/lytx:v1 # image we pushed
          imagePullPolicy: Always
          ports:
            - containerPort: 9191

